$background = rgba(1b1719ee)
$background_dim = rgba(1b1719bb)
$surface = rgba(2d292bcc)
$hover = rgba(383335cc)
$border = rgba(433d40dd)
$accent = rgba(ffae72ff)
$accent_hover = rgba(ffc28eff)
$accent_active = rgba(ff9750ff)
$text = rgba(f2ede8ff)
$text_secondary = rgba(cdbbb6ff)
$text_disabled = rgba(8c8480ff)
$success = rgba(8ccf7eff)
$warning = rgba(ffcc66ff)
$error = rgba(ef6b73ff)
$info = rgba(79b8ffff)
