foreground #ada594
background #292724
selection_foreground #ada594
selection_background #3d3a34

cursor #ffae72
cursor_text_color #292724
url_color #ffae72

active_border_color #ffae72
inactive_border_color #292724
bell_border_color #ffae72
visual_bell_color none

wayland_titlebar_color #3d3a34
tab_bar_background #3d3a34
active_tab_foreground #fbfaf9
active_tab_background #292724
inactive_tab_foreground #b9b1ac
inactive_tab_background #3d3a34

color0 #292724
color1 #816f4b
color2 #ec9255
color3 #ffb380
color4 #ffae72
color5 #ec9255
color6 #ac8e53
color7 #ada594

color8 #7e7767
color9 #f29d63
color10 #3d3a34
color11 #615c51
color12 #ffc28e
color13 #ddcba6
color14 #e58748
color15 #f2ead9
