foreground #f2ede8
background #1b1719
selection_foreground #1b1719
selection_background #ffae72

cursor #ffae72
cursor_text_color #1b1719
url_color #ffc28e

active_border_color #ffae72
inactive_border_color #433d40
bell_border_color #ef6b73
visual_bell_color none

wayland_titlebar_color #1b1719
tab_bar_background #1b1719
active_tab_foreground #1b1719
active_tab_background #ffae72
inactive_tab_foreground #cdbbb6
inactive_tab_background #2d292b

color0 #1b1719
color1 #ef6b73
color2 #8ccf7e
color3 #ffae72
color4 #79b8ff
color5 #ffc28e
color6 #cdbbb6
color7 #f2ede8

color8 #8c8480
color9 #ef6b73
color10 #8ccf7e
color11 #ffcc66
color12 #79b8ff
color13 #ffc28e
color14 #cdbbb6
color15 #fff4ed
